### PR TITLE
Make SelectValuesProvider to accept object instead of only strings.

### PR DESCRIPTION
**Pull request by calcacuervo**

### CODE REVIEW

**Comment by pefernan** [comment]
@kie-ci Sorry, I totally forgot this PR 

@calcacuervo hi, can you explain a little why do you need this change? I need some background to check it.

**Comment by psiroky** [comment]
@pefernan the second message was side effect of some large config changes on Jenkins, not an call to review :)

**Comment by psiroky** [comment]
But I guess it worked anyway as we should take a look at the PR.

**Comment by calcacuervo** [comment]
@pefernan  Hi Pere. I had to implement it to be able to retrieve objects from a provider, instead of just being able to return an string. For example, I created a JPASelectValues provider, which will query a database and display the list of customers, but have the object itself to map it back to the process instead of an string.

**Comment by porcelli** [comment]
@pefernan do you mind review this PR?

**Comment by pefernan** [comment]
Since we are moving to the new Form Modeler this PR makes no sense.

@manstis do you agree?

**Comment by manstis** [comment]
@pefernan It's your call, but I tend to agree (it can be closed without merge). This PR targets ```master``` which I guess is at best deprecated; and we're unlikely to release a maintenance version from this repository. @pefernan If the concept is still viable for the new Form Modeller perhaps liaise with @calcacuervo to have it resubmitted for the new Form Modeller.

**Pull request closed without merging**
