### PR TITLE
[6.5.x] RHBPMS-4768 - On Change Script Code does not work properly for Short …

### PR DESCRIPTION
**Pull request by tsurdilo**
…Date/Timestamp fields in Form Modeler - adding onSelect event handling

### CODE REVIEW

**Comment by tsurdilo** [comment]
@jsoltes please test this to make sure its ok. I am new to the form modeler code so good testing is needed here :) thanks!

**Comment by mbiarnes** [comment]
@jsoltes if you checked this pls approve this PR so it can be merged

**Comment by jsoltes** [comment]
@tsurdilo @mbiarnes after it builds, i will test the binaries, and if it is ok, I will approve.

**Comment by jsoltes** [comment]
I am afraid this still does not fix the customer requirement. "The alert is not fired if you click on the field or change the date." I think the customer also expects it to be fired not only when clicking on the datepicker icon, but also when clicking on different date in the (already opened) datepicker. The attached video explains what I mean.

[Screencast_08-18-2017.zip](https://github.com/kiegroup/jbpm-form-modeler/files/1233725/Screencast_08-18-2017.zip)

**Comment by tsurdilo** [comment]
@jsoltes onSelect should capture the clicks of individual dates inside the opened datepicker. In your video behavior is same as before - if have time mind clearing browser cache and retest?

**Comment by jsoltes** [comment]
@tsurdilo well I tested it on 7.3.x branch, looks like it doesn't work there (tried it also in incognito mode). But I trust you that it works here and on master and I don't want to postpone it more before it gets merged, so I will approve and test it on the resuting 6.5 build.

**Pull request merged**
